package com.worlize.interactivity.iptscrae
{
	import com.worlize.interactivity.iptscrae.command.*;
	
	public class WorlizeIptscraeCommands
	{
		public static var commands:Object = {
			"ALARMEXEC": ALARMEXECCommand,
			"CHAT": SAYCommand,
			"CLEARLOOSEPROPS": CLEARLOOSEPROPSCommand,
			"CLIENTTYPE": CLIENTTYPECommand,
			"DEST": DESTCommand,
			"DIMROOM": DIMROOMCommand,
			"ENABLEWEBCAM": ENABLEWEBCAMCommand,
			"GETSPOTLOC": GETSPOTLOCCommand,
			"GLOBALMSG": GLOBALMSGCommand,
			"GOTOROOM": GOTOROOMCommand,
			"HIDEAVATARS": HIDEAVATARSCommand,
			"ID": MECommand,
			"INSPOT": INSPOTCommand,
			"IPTVERSION": IPTVERSIONCommand,
			"KILLUSER": KILLUSERCommand,
			"LOCALMSG": LOCALMSGCommand,
			"LOCK": LOCKCommand,
			"LOGMSG": LOGMSGCommand,
			"MACRO": MACROCommand,
			"MOVE": MOVECommand,
			"ME": MECommand,
			"MIDILOOP": MIDILOOPCommand,
			"MIDIPLAY": MIDIPLAYCommand,
			"MIDISTOP": MIDISTOPCommand,
			"MOUSEPOS": MOUSEPOSCommand,
			"NAKED": NAKEDCommand,
			"NBRDOORS": NBRDOORSCommand,
			"NBRROOMUSERS": NBRROOMUSERSCommand,
			"NBRSPOTS": NBRSPOTSCommand,
			"NOTIFICATION": NOTIFICATIONCommand,
			"POSX": POSXCommand,
			"POSY": POSYCommand,
			"PRIVATEMSG": PRIVATEMSGCommand,
			"ROOMID": ROOMIDCommand,
			"ROOMNAME": ROOMNAMECommand,
			"ROOMUSER": ROOMUSERCommand,
			"ROOMHEIGHT": ROOMHEIGHTCommand,
			"ROOMWIDTH": ROOMWIDTHCommand,
			"SAY": SAYCommand,
			"SAYAT": SAYATCommand,
			"SELECT": SELECTCommand,
			"SERVERNAME": SERVERNAMECommand,
			"SETALARM": SETALARMCommand,
			"SETCOLOR": SETCOLORCommand,
			"SETFACE": SETFACECommand,
			"SETLOC": SETLOCCommand,
			"SETLOCLOCAL": SETLOCLOCALCommand,
			"SETPOS": SETPOSCommand,
			"SHOWAVATARS": SHOWAVATARSCommand,
			"SPOTDEST": SPOTDESTCommand,
			"SPOTIDX": SPOTIDXCommand,
			"NETGOTO": NETGOTOCommand,
			"ROOMMSG": ROOMMSGCommand,
			"STATUSMSG": STATUSMSGCommand,
			"SUSRMSG": SUSRMSGCommand,
			"SOUND": SOUNDCommand,
			"UNLOCK": UNLOCKCommand,
			"USERID": USERIDCommand,
			"USERNAME": USERNAMECommand,
			"WHOCHAT": WHOCHATCommand,
			"WHOME": USERIDCommand,
			"WHONAME": WHONAMECommand,
			"WHOPOS": WHOPOSCommand,
			"WHOTARGET": WHOTARGETCommand
		};
	}
}